name: CI Pipeline testing & linting

on:
  push:
    branches:
      - main
      - develop
      - tests_funcionales
      - merge_branches
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI (Tests, Linting & Analysis)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # --------------------------------------------------
      # Paso de Tests Unitarios (no bloqueante)
      - name: Run JUnit Tests
        working-directory: Backend/ot_backend
        run: mvn -P local clean test
        continue-on-error: true   # <— Aquí evitas que el fallo de tests detenga el job

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Backend/ot_backend/target/surefire-reports/*.xml
      # --------------------------------------------------

      # Static Code Analysis: Checkstyle
      - name: Run Checkstyle
        working-directory: Backend/ot_backend
        continue-on-error: true
        run: mvn -q checkstyle:check

      # PMD
      - name: Run PMD
        working-directory: Backend/ot_backend
        continue-on-error: true
        run: mvn -q pmd:check

      # SpotBugs
      - name: Run SpotBugs
        working-directory: Backend/ot_backend
        continue-on-error: true
        run: mvn -q spotbugs:check

      # OWASP Dependency Check
      - name: OWASP Dependency-Check
        working-directory: Backend/ot_backend
        continue-on-error: true
        run: mvn -q org.owasp:dependency-check-maven:check -Ddependency-check.failBuildOnCVSS=7

      # SonarQube Analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarQube Analysis
        working-directory: Backend/ot_backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ander-666_Votacion-OT_0a493e13-23e8-4847-9c9a-83138ab143fc -Dsonar.projectName='Votacion-OT'
