name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          
      - name: Build with Maven
        working-directory: Backend/ot_backend 
        run: mvn -P local clean install
    
      - name: Build and run tests
        run: mvn clean test
