name: Terraform CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - merge_branches   # antes era merge_branches, ahora apuntamos a main

env:
  TF_WORKING_DIR: terraform
  TF_VAR_aws_region:      ${{ secrets.AWS_REGION }}
  TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Terraform Init (remote state fixed)
        run: terraform init -input=false \
          -backend-config="bucket=mi-bucket-terraform-state" \
          -backend-config="key=ci/terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="dynamodb_table=mi-tabla-lock"

      # ➡️ Destruye todo lo existente antes de volver a crear
      - name: Terraform Destroy (clean slate)
        run: terraform destroy -auto-approve

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -out=tfplan \
            -input=false \
            -no-color
          terraform show -no-color tfplan > plan.txt

      - name: Upload Plan Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            tfplan
            plan.txt

      - name: Comment Plan on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Terraform Plan"
          message: |
            ```
            ${{ steps.plan.outputs.stdout || 'Consulta plan.txt (artifact)' }}
            ```

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: terraform apply -input=false -auto-approve tfplan
