name: Terraform CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - merge_branches

env:
  TF_WORKING_DIR: terraform
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      # 1. Checkout del repositorio (incluye subm贸dulos si los hubiera)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Instalaci贸n de Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 3. Credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 4. Inicializar Terraform
      - name: Terraform Init
        run: terraform init -input=false -backend-config="key=ci/${{ github.sha }}"

      # 5. Validar sintaxis y configuraci贸n
      - name: Terraform Validate
        run: terraform validate

      # 6. Comprobar formato
      - name: Terraform Format Check
        run: terraform fmt -check

      # 7. Generar plan y guardarlo en un archivo
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -out=tfplan \
            -input=false \
            -no-color
          terraform show -no-color tfplan > plan.txt

      # 8. Subir el plan como artifact (para inspecci贸n manual si falla algo)
      - name: Upload Plan Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ${{ env.TF_WORKING_DIR }}/tfplan
            ${{ env.TF_WORKING_DIR }}/plan.txt

      # 9. Comentar el plan en el PR (texto plano, sin HCL embebido)
      - name: Comment Plan on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Terraform Plan"
          message: |
            ${{ steps.plan.outputs.stdout || 'Plan generado en plan.txt (artifact)' }}

      # 10. Aplicar cambios
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan

      # 11. Subir el estado de Terraform como artifact ZIP
      - name: Upload Terraform State
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: ${{ env.TF_WORKING_DIR }}/terraform.tfstate
